### ISSUE TITLE
Adapt repo to new rust-optimizer

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmwasm-template#49]
The latest https://github.com/CosmWasm/rust-optimizer writes into a different directory.

- [ ] Update `static WASM: &[u8] = include_bytes!("../contract.wasm");`  in `tests/integration.rs`
- [ ] ...

**Comment by ethanfrey** [comment]
And use the latest version.. it is 0.11.4 I think now and makes smaller and cheaper executables
