### ISSUE TITLE
Upgrade Rust version in CI setup

### ISSUE THREAD

**Issue by webmaster128** [CosmWasm/cosmwasm-template#55]
Right now we use 1.44.1 in `.circleci/config.yml` and `.github/workflows/Basic.yml`, which is unsupported by CosmWasm.

**Comment by venkattejaRaavi** [comment]
What is the latest version then?

**Comment by webmaster128** [comment]
The min Rust version is always documented in the [CosmWasm CHANGELOG](https://github.com/CosmWasm/cosmwasm/blob/master/CHANGELOG.md). For

- CosmWasm 0.11 we require Rust >= 1.45.2,
- CosmWasm 0.13 (unreleased) we requeste Rust >= 1.48.0

The CI testing should always happen on the lowest supported version.

**Comment by ethanfrey** [comment]
Let's use 1.53 now in CI

**Comment by maurolacy** [comment]
Closed by #77.
