### ISSUE TITLE
Add gitpod support

### ISSUE THREAD

**Issue by ethanfrey** [CosmWasm/cosmwasm-template#58]
Inspired by https://github.com/cosmos/cosmos-sdk/pull/8090

We can set this up, so after creating a new contract from template, it will have gitpod support to edit it. Ideally, the `cargo generate` command can be part of that, but that seems a bit more complex.

The final result would be a user could click a button or two to open up a web IDE with a contract skeleton for their newly created contract (with their custom name). This should somehow be connected to a new github repo under their username. When they make the changes on gitpod, they get saved to their github repo.

**Comment by orkunkl** [comment]
I am working on this. Makes setting up environment for Dev Academy much simpler

**Comment by orkunkl** [comment]
Projects based on cosmwasm-template will have gitpod by default when after this feature is enabled. No extra setup required to make it work with `cargo generate`

**Comment by ethanfrey** [comment]
I just approved it. Happy for you to try it out.

Do you need to authorise GitHub after each `cargo generate`?
I just added cosmwasm-template to gitpod

**Comment by orkunkl** [comment]
Authorization is needs to be done once on newly generated repo by owner.

**Comment by PotasticPotatoe** [comment]
i noticed some exceptions ex: 

invalid character `{` in package name: `{{project-name}}`, the first character must be a Unicode XID start character (most letters or `_`)
  
 During initial stand up. Maybe we could change that in the future?
 
 For the todo could we link them to the extension and a screen shot of the button to press?

**Comment by PotasticPotatoe** [comment]
Besides that I think we're good here.

This solves the issue of specific systems not supporting ARM and reduces friction of developing (less steps to set up dev environment).

**Comment by orkunkl** [comment]
@PotasticPotatoe gitpod runs `cargo build` on launch to cache libraries on the launch. Since `cosmwasm-template` is not a rust project, this is expected. You are supposed to use gitpod on projects generated using cosmwasm-template repo.

**Comment by PotasticPotatoe** [comment]
ack, closing this ticket if no other issues

**Comment by orkunkl** [comment]
Great!
