### ISSUE TITLE
my_first_contract.wasm interraction error

### ISSUE THREAD

**Issue by byjtew93** [CosmWasm/cosmwasm-template#64]
Hi everyone,

At this step of the main tutorial: https://docs.terra.money/contracts/tutorial/interacting.html#uploading-code

We have a file in the 'artifacts' folder named 'my_first_contract.wasm'.
We are supposed to run this command: `terracli tx wasm store my-first-contract.wasm --from test1 --chain-id=localterra --gas=auto --fees=100000uluna --broadcast-mode=block`

This command fails (at least in Ubuntu 20.x.x LTS).
The "\_" character isn't recognised correctly by the command AND the command is searching for a file in the root of the working directory.
That's why you need to rename the file, removing every "\_" AND specify the path in the command.

This is the correct command to run `terracli tx wasm store artifacts/myfirstcontract.wasm --from test1 --chain-id=localterra --gas=auto --fees=100000uluna --broadcast-mode=block`.

Special thank's to `davidkohcw#4184`

**Comment by webmaster128** [comment]
Please reach out to Terra for issues in Terra documentation.
